def menu():
    print("\n---------------Menu---------------")
    print("1) Get all creds of specific app")
    print("2) Get all apps in database")
    print("3) Find accounts using email/phone")
    print("4) Add new app to database")
    print("5) Delete app from database")
    print("6) Generate password")
    print("7) Exit")
    print("------------------------------------")
